CREATE DATABASE College;

CREATE DATABASE IF NOT EXISTS College;
DROP DATABASE IF EXISTS Company;
USE College;

CREATE TABLE Student (
	ID INT PRIMARY KEY,
    Name VARCHAR(50),
    Age INT NOT NULL
);

INSERT INTO Student VALUES(1, "Atef", 23);
INSERT INTO Student VALUES(2, "Hafsa", 23);

SELECT * FROM Student;

SHOW DATABASES;
SHOW TABLES;